### ISSUE TITLE
Issue with Separator in retrieve_from_bed.py Causing Misalignment in variant_effects_disease.bed

### ISSUE THREAD

**Issue by yangzhao1230** [frederikkemarin/BEND#48]
Hi, 

Thanks for your greate work!

I've encountered an issue when attempting to run the SNP-related tasks. The script `retrieve_from_bed.py` utilizes `\s+` as the separator for reading data files. This works well for most cases, but I noticed that in the `variant_effects_disease.bed` file, some labels contain spaces, such as 'Likely benign'. This results in an incorrect split when reading the file and subsequent misalignment of the data columns.

To work around this issue, I've changed the separator to `\t` (tab), which has resolved the problem for me.

**Comment by fteufel** [comment]
Hi @yangzhao1230 yes, it should be `\t` indeed. Will fix.
