### ISSUE TITLE
'N' exists in variant datasets

### ISSUE THREAD

**Issue by yangzhao1230** [frederikkemarin/BEND#49]
I noticed you pre pre-set embedding_idx in variant taks. However, there exists 'N' in such datasets, which may alter the embedding_idx, because the 'N' occupied a whole token.

**Comment by yangzhao1230** [comment]
I only raise the issue when using NTs, as NTs use non-overlapping 6-mer tokenzier.

**Comment by fteufel** [comment]
Thanks for reporting this! It should be fixable by using upsampling also for NT models. I'll investigate whether results are affected by this and fix it in a PR.
