### ISSUE TITLE
dirty data exists in variant dataset

### ISSUE THREAD

**Issue by yangzhao1230** [frederikkemarin/BEND#51]
Upon reviewing the genomic data, i have identified inconsistencies between some reference nucleotides and those in the genome. For instance, within the expression dataset, two instances of data were detected where their corresponding reference nucleotides in the genome are both C.
![image](https://github.com/frederikkemarin/BEND/assets/52462696/4eea52cb-a996-4691-9a34-deb29b18e30a)
![image](https://github.com/frederikkemarin/BEND/assets/52462696/53215fdd-92ea-4be3-959e-6e86c1977cc6)

**Comment by yangzhao1230** [comment]
It seems that the problem is isolated to the expression dataset, potentially occurring during the transition from the hg37 to hg38 genomic assembly.

**Comment by fteufel** [comment]
Thanks @yangzhao1230 - I'll remove these samples from the dataset. 

Will close the issue once the file online is replaced.

**Comment by fteufel** [comment]
replaced
