### ISSUE TITLE
Inconsistent number of classes for histone modification task

### ISSUE THREAD

**Issue by kirill-vish** [frederikkemarin/BEND#52]
Hello, thanks for opensourcing your benhcmark. I have a question regarding the histone modification task. In the paper you mention that target for histone modification task should be a vector of the length **19**:
<img width="773" alt="Screenshot 2024-03-15 at 2 24 44 PM" src="https://github.com/frederikkemarin/BEND/assets/150828001/fd3f8fcb-1f2d-4909-b4bb-79a8faf40a9a">

However, in the configs in the codebase you can see that `histone_modification_label_dim: 18` in `datadims.yaml`. This affects the length of the label vector. Shouldn't the `histone_modification_label_dim` be set to 19 instead?

**Comment by fteufel** [comment]
Hi @kirill-vish, thanks for finding this!

It looks like an error in the data section of the paper, the number is actually 18 (We also have 18 not only in the code, but in the dataset + all supplementary results).

So 18 should be correct. We will fix the paper.

**Comment by kirill-vish** [comment]
I see, thanks for the reply.
