### ISSUE TITLE
Fix broken link

### ISSUE THREAD

**Issue by tdsone** [frederikkemarin/BEND#54]
In the README the link to the data folder is broken (see: https://sid.erda.dk/cgi-sid/ls.py?share_id=eXAmVvbRSW). 

Should be https://sid.erda.dk/cgi-sid/ls.py?share_id=aNQa0Oz2lY&current_dir=data&flags=f

**Comment by frederikkemarin** [comment]
Yes. This is fixed now. Thank you for bringing our attention to it.
