### ISSUE TITLE
 Discrepancy in Genome Versions Used for Chromatin Accessibility Compared to Other ENCODE-Based Studies

### ISSUE THREAD

**Issue by yangzhao1230** [frederikkemarin/BEND#55]
Why is the GRCh37 genome used for the chromatin accessibility task while histone modification and CpG methylation tasks, which also source their datasets from ENCODE, utilize the GRCh38 genome? What accounts for the different genome versions being used across these related tasks?
![image](https://github.com/frederikkemarin/BEND/assets/52462696/de49e29a-9361-4b81-91ef-23b5f73592ef)

**Comment by fteufel** [comment]
Hi @yangzhao1230 , we used GRCh37 for this task because it was faster for us to process the data this way. There's no further biological reason behind it.
