### ISSUE TITLE
Slow Training for Downstream Tasks with Low GPU Utilization

### ISSUE THREAD

**Issue by 1159556229** [frederikkemarin/BEND#57]
Hello,

I am currently experiencing significant slow-downs during the training process of downstream tasks. Notably, the GPU utilization is nearly zero, which seems unusualI. I suspect this might be related to the compressed nature of the dataset (webdataset), but I'm not entirely sure.

Additionally, I have attempted to use multi-GPU parallelism to enhance the training speed, but unfortunately, there has been no noticeable improvement in performance. This situation leads me to seek advice or recommendations on methods to accelerate the training process.

Could you please provide any tips on how to optimize training speed for such scenarios? Moreover, based on your experience, how long does it typically take to run downstream tasks with similar settings? For reference, I am using a single V100 GPU to process 256-dimensional features on the Histone modification task, and it takes over a day to complete.

Thank you for your assistance.

**Comment by fteufel** [comment]
Hi,

One thing to adjust is the number of workers for dataloading, `num_workers` in the config. Compression might of course also slow things down, but was absolutely necessary for us to work on the systems we had available. Hence we chose to work with webdataset. We haven't used multi GPU training so far.

That being said, training on V100 for some model-task combinations did take multiple days.

**Comment by 1159556229** [comment]
Thank you so much for your help!

**Comment by 1159556229** [comment]
Thank you so much for your help!
