### ISSUE TITLE
Incorrect DNABERT behavior?

### ISSUE THREAD

**Issue by canallee** [frederikkemarin/BEND#58]
Hi, thanks for the great efforts in organizing this easy-to-use benchmark suite!

I noticed a potentially incorrect implementation of `DNABertEmbedder`:
![DNABERT](https://github.com/user-attachments/assets/e3985678-d1ee-42ba-b432-4dad4ca418f3)
In the `embed()` function, any input sequence is first k-merized, tokenized, and padded to sequence length +2. For a sequence of length 512 (as in the case for all tasks except for Gene finding and Enhancer Annotation), the `model_input` would have a length of 514. 

In the current implementation, the `model_input` would be 1) split into 2 `chunk `of length 512 and 2, 2) combine the embeddings of shape (512,768) (2,768) -> (514,768), and 3) remove the first and last position embedding to be (512,768). This won't happen if line 238 is ` if model_input.shape[1] > 514:`

**Comment by fteufel** [comment]
Yes, I think your description of the current implementation is correct. We chunk, combine, and remove the special tokens.  What would be the correct behaviour you expect?

**Comment by canallee** [comment]
Thanks so much for the quick reply! Since the DNABERT paper, "DNABERT takes a sequence with a max length of 512 as input", I would expect that a sequence of length 512 would not be chunked. By changing `if model_input.shape[1] > 514` to `if model_input.shape[1] > 512` would fix this, since the sequence of length 512 would have a tokenized length of 514.

**Comment by fteufel** [comment]
You're right -  the padding should not be there, it's unnecessary.
```python
  #    padding = 'max_length',
  #    max_length = len(sequence[0])+2, 
```
Commenting out these two lines should give the expected behavior.  I'll do a few more checks to be sure and then update the code.

**Comment by canallee** [comment]
Thanks for the fix! One additional thing, the `upsample_embeddings` for `dnabert6` in emb config file should be set to true, otherwise the embedding would have a length of 507 instead of 512.  

I just tested it, and adding this fix would have the correct behavior as described in the comment for `_repeat_embedding_vectors`.
